// This snippet file was generated by processing the source file:
// ./messaging-next/service-worker.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START messaging_init_in_sw_modular]
import { initializeApp } from "firebase/app";
import { getMessaging } from "firebase/messaging/sw";

// Initialize the Firebase app in the service worker by passing in
// your app's Firebase config object.
// https://firebase.google.com/docs/web/setup#config-object
const firebaseApp = initializeApp({
    apiKey: "AIzaSyAQyKGOGj6-WZD1IENAX1LynOz_GbERNw4",
    authDomain: "elite-service-92d53.firebaseapp.com",
    databaseURL: "https://elite-service-92d53-default-rtdb.europe-west1.firebasedatabase.app",
    projectId: "elite-service-92d53",
    storageBucket: "elite-service-92d53.appspot.com",
    messagingSenderId: "336956340236",
    appId: "1:336956340236:web:e62786b00809d449699629",
    measurementId: "G-QSF4E7NRMD"
});

// Retrieve an instance of Firebase Messaging so that it can handle background
// messages.
const messaging = getMessaging(firebaseApp);
// [END messaging_init_in_sw_modular]